import chalk from 'chalk';

const ANSI_RE = /\x1b\[[0-9;]*m/g;

export function stripAnsi(str) {
  return str.replace(ANSI_RE, '');
}

function getGrade(score) {
  if (score >= 90) return 'A';
  if (score >= 75) return 'B';
  if (score >= 60) return 'C';
  if (score >= 40) return 'D';
  return 'F';
}

function getScoreColor(score) {
  if (score >= 90) return chalk.greenBright;
  if (score >= 75) return chalk.green;
  if (score >= 60) return chalk.blue;
  if (score >= 40) return chalk.yellow;
  return chalk.red;
}

function getSeverityColor(severity) {
  switch (severity) {
    case 'critical': return chalk.red;
    case 'warning': return chalk.yellow;
    case 'info': return chalk.blue;
    case 'pass': return chalk.green;
    default: return chalk.white;
  }
}

function getSeverityIcon(severity) {
  switch (severity) {
    case 'critical': return '\u2717';
    case 'warning': return '\u26A0';
    case 'info': return '\u2139';
    case 'pass': return '\u2713';
    default: return ' ';
  }
}

function boxLine(text, width) {
  const plain = stripAnsi(text);
  const pad = Math.max(0, width - plain.length);
  return `  \u2502 ${text}${' '.repeat(pad)} \u2502`;
}

function box(lines, width = 38) {
  const top = `  \u256D${'─'.repeat(width + 2)}\u256E`;
  const bottom = `  \u2570${'─'.repeat(width + 2)}\u256F`;
  const boxed = lines.map((l) => boxLine(l, width));
  return [top, ...boxed, bottom].join('\n');
}

export function formatTerminal(result, cwd) {
  const { score, results } = result;
  const grade = getGrade(score);
  const colorFn = getScoreColor(score);
  const lines = [];

  // Header
  lines.push('');
  lines.push(box([
    '',
    `${'       '}rigscore v0.1.0`,
    '  AI Dev Environment Security Scan',
    '',
  ]));
  lines.push('');
  lines.push(`  Scanning ${cwd} ...`);
  lines.push('');

  // Check scores
  for (const r of results) {
    const checkScore = Math.round((r.score / 100) * r.weight);
    const icon = r.score >= 70 ? chalk.green('\u2713') : chalk.red('\u2717');
    const name = r.name.padEnd(30, '.');
    lines.push(`  ${icon} ${name} ${checkScore}/${r.weight}`);
  }

  lines.push('');

  // Score box
  const scoreStr = colorFn(`YOUR RIGSCORE: ${score}/100`);
  const gradeStr = colorFn(`Grade: ${grade}`);
  lines.push(box([
    '',
    `        ${scoreStr}`,
    `        ${gradeStr}`,
    '',
  ]));
  lines.push('');

  // Findings by severity
  const allFindings = results.flatMap((r) =>
    r.findings.map((f) => ({ ...f, checkName: r.name })),
  );

  for (const severity of ['critical', 'warning', 'info']) {
    const items = allFindings.filter((f) => f.severity === severity);
    if (items.length === 0) continue;

    const label = severity.toUpperCase();
    const color = getSeverityColor(severity);
    lines.push(`  ${color(`${label} (${items.length})`)}`);

    for (const item of items) {
      const icon = getSeverityIcon(severity);
      lines.push(`  ${color(icon)} ${item.title}`);
      if (item.detail) {
        lines.push(`    ${chalk.dim('\u2192')} ${item.detail}`);
      }
      if (item.remediation) {
        lines.push(`    ${chalk.dim('\u2192')} Fix: ${item.remediation}`);
      }
      if (item.learnMore) {
        lines.push(`    ${chalk.dim('\u2192')} Learn more: ${item.learnMore}`);
      }
      lines.push('');
    }
  }

  // CTA
  lines.push(`  ${'─'.repeat(40)}`);
  lines.push('');
  lines.push('  Want a full audit with hardened configurations deployed?');
  lines.push(`  ${chalk.cyan('\u2192')} https://backroadcreative.com/ai-agent-security-audit`);
  lines.push('');
  lines.push(`  Share your score: ${chalk.dim('npx rigscore --badge')}`);
  lines.push('');

  return lines.join('\n');
}

export function formatJson(result) {
  return JSON.stringify(result, null, 2);
}

export function formatBadge(result) {
  const { score } = result;
  const color = score >= 90 ? 'brightgreen' : score >= 75 ? 'green' : score >= 60 ? 'blue' : score >= 40 ? 'yellow' : 'red';
  const url = `https://img.shields.io/badge/rigscore-${score}%2F100-${color}`;
  return `![rigscore](${url})\n\nGenerated by [rigscore](https://github.com/backroadcreative/rigscore)`;
}
